export enum STAFF_PERMISSION {
  VIEW_STATION = "VIEW_STATION",
  UPDATE_STATION = "UPDATE_STATION",
  MANAGE_STAFF = "MANAGE_STAFF",
  ASSIGN_SHIFT = "ASSIGN_SHIFT",

  VIEW_TRAIN = "VIEW_TRAIN",
  MANAGE_TRAIN_SCHEDULE = "MANAGE_TRAIN_SCHEDULE",
  UPDATE_TRAIN_STATUS = "UPDATE_TRAIN_STATUS",

  CREATE_REPORT = "CREATE_REPORT",
  VIEW_REPORT = "VIEW_REPORT",

  VIEW_STAFF = "VIEW_STAFF",

  VIEW_SCHEDULE = "VIEW_SCHEDULE",

  CREATE_TICKET = "CREATE_TICKET",
  CANCEL_TICKET = "CANCEL_TICKET",
  UPDATE_TICKET = "UPDATE_TICKET",

  VIEW_PASSENGER = "VIEW_PASSENGER",

  VIEW_ASSIGNED_TRAIN = "VIEW_ASSIGNED_TRAIN",
  VIEW_ROUTE = "VIEW_ROUTE",
  UPDATE_TRIP_STATUS = "UPDATE_TRIP_STATUS",

  CREATE_INCIDENT_REPORT = "CREATE_INCIDENT_REPORT",

  UPDATE_SIGNAL = "UPDATE_SIGNAL",
  MANAGE_SIGNAL_STATUS = "MANAGE_SIGNAL_STATUS",

  MANAGE_TRACK = "MANAGE_TRACK",
  UPDATE_TRACK_STATUS = "UPDATE_TRACK_STATUS",
  VIEW_TRACK = "VIEW_TRACK",

  VIEW_PLATFORM = "VIEW_PLATFORM",
  MANAGE_PLATFORM = "MANAGE_PLATFORM",
  UPDATE_ARRIVAL_DEPARTURE = "UPDATE_ARRIVAL_DEPARTURE",

  CREATE_SECURITY_REPORT = "CREATE_SECURITY_REPORT",
  VIEW_INCIDENT = "VIEW_INCIDENT",

  VIEW_MAINTENANCE_TASK = "VIEW_MAINTENANCE_TASK",
  CREATE_MAINTENANCE_REPORT = "CREATE_MAINTENANCE_REPORT",
  UPDATE_MAINTENANCE_STATUS = "UPDATE_MAINTENANCE_STATUS",

  UPDATE_EQUIPMENT_STATUS = "UPDATE_EQUIPMENT_STATUS",

  VIEW_PAYMENT = "VIEW_PAYMENT",
  MANAGE_TRANSACTION = "MANAGE_TRANSACTION",
  VIEW_FINANCIAL_REPORT = "VIEW_FINANCIAL_REPORT",

  MANAGE_ATTENDANCE = "MANAGE_ATTENDANCE",
  MANAGE_LEAVE = "MANAGE_LEAVE",

  MANAGE_SYSTEM = "MANAGE_SYSTEM",
  VIEW_LOGS = "VIEW_LOGS",
  MANAGE_DEVICES = "MANAGE_DEVICES",

  HANDLE_COMPLAINT = "HANDLE_COMPLAINT",
  CREATE_SUPPORT_TICKET = "CREATE_SUPPORT_TICKET",
}
